import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Next.js의 라우터 그룹 기능
// 폴더명을 괄호로 감싸면 (예: (with-searchbar)) URL 경로에 영향을 주지 않으면서
// 관련된 페이지들을 논리적으로 그룹화할 수 있습니다.
// 이는 코드 구조를 깔끔하게 유지하면서도 URL 구조를 단순하게 유지할 수 있게 해줍니다.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 레이아웃 중첩 (Layout Nesting)
// Next.js의 레이아웃은 중첩될 수 있으며, 각 레이아웃은 자신의 하위 경로에 적용됩니다.
// app/layout.tsx는 루트 레이아웃으로, 모든 페이지에 적용됩니다.
// 하위 경로에 있는 layout.tsx는 해당 경로와 그 하위 경로에만 적용됩니다.
// 레이아웃은 중첩되어 적용되므로, 상위 레이아웃의 스타일과 기능이 하위 레이아웃에 상속됩니다.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
